name: CI
on:
  pull_request:
  push:

jobs:
  firmware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: arduino
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install platformio
      - run: pio pkg update
      - run: pio run

  hardware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hardware
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run mohawk
